name: 'Test'

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2
    - name: Test build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target rtl433_usb_to_mqtt \
          --image rtl_433_usb_to_mqtt \
          --docker-hub reichley
